sudo: false
cache:
  directories:
  - $HOME/.gradle
  - .gradle
env:
  global:
  - USER=ApiSecRay
    # BINTRAY API KEY:
  - secure: XgXG6UVWg8+MpXXaNH0c3w3Tsp9XBi1eXPbGUi16ztZUS/DVDnCbrFFX1ABXz4Dw+qCER67hjtcL6O0bczt1oJFFurC1tMzSXqZSrVIDcDAEVKCi08dy73yxm0QX4HFWg/z67O0DzJi8teYMcItSgBAsKbhnVEV+mnYxS/wR86c=

language: java
jdk:
- openjdk7
install: true
script: ./gradlew build
after_success:
- ./deploy_to_bintray.sh
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key:
    secure: dAEw8CE7ZaGY5VV0MMhAWTI4Eg4tBJnbdfGt+nV5yWbxEagn0WfJAkZTpVMhqTJrrLoJY7D3tv+cKzNTaHRUXJrijjWEbEppqK057n//cbPdPsi5On7d8o2rssXLKuV5x5Lc9u8jy/uAyR1BwXdio02JtzgfcTKuLyhIwTU+/SJsRivfOZh1CBDul30KTS5w+N7HUfFv2ciJ0nnH0eYdfVIpbmsA0x2CpFSXacJDQKPsFHhTM93OEbpQYHYqgYGNanrpQ19S8YOQieFn4TXWsKW+tPnHDLnVEkEdxSA7PuXqF7KEjHjc54S8FZdYGhGAJ3VF07LFgVhBm+qBggU8Uowr6MZdmI5a/HtqutzYPEu2jkvmWgbZeONEMrQULgVk2OF2abdgzLS/FHO5H69Bg3RNfKIGHgClzT4g26xHMS9xTuH/6gw5S9O2S6M2/7CBeKRqbuQrcynec43dHzavkngCW1d9b/fcqdL28CR8wMosHNGoDTnyqTOqAjIYi+mEvzyWRGO/rXpMxLWmEK6Ow9YTOPxzLauSF57+7DdyxXFirGxEy89K0LGMzeQXWPivkN2HZ+wnO6vKPMxaBsQJIIANRDr6v6886i2TC12FdzKq+aJA+WkECJjbMfmxausfCf1WJKotuPOMU/DGaMjGlrcTW14+wL4zWqKtieUulgo=
  file_glob: true
  file:
  - build/libs/*
  on:
    repo: restful-api-description-language/radl-specification
    tags: true
    all_branches: true
