sudo: false # Run on containers rather than VMs to enable caching
cache:
  directories:
  - $HOME/.gradle
  - .gradle
env:
  global:
  - USER=ApiSecRay
    # BINTRAY API KEY:
  - secure: XgXG6UVWg8+MpXXaNH0c3w3Tsp9XBi1eXPbGUi16ztZUS/DVDnCbrFFX1ABXz4Dw+qCER67hjtcL6O0bczt1oJFFurC1tMzSXqZSrVIDcDAEVKCi08dy73yxm0QX4HFWg/z67O0DzJi8teYMcItSgBAsKbhnVEV+mnYxS/wR86c=

language: java
jdk:
- openjdk7
install: true
script: ./gradlew build


## Notifications
notifications:
  slack:
    secure: LJfuvagJjFqaoA8AJQtfLOtymOzpifA2qUqA1XI5Kd67sVFY5BViIHZ/+qy3jV+Ve7Msl8St+XiB9zrLqKOxFNNaFvYZYgpn4fb4RDxVWipZrVY9/DRwEImzuWNsx1Il7rn9zWK0jgmIyK2DK6wtWPnZUTinHGPIw3RtvR22AyA=
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9964f490aeaa2be3c3c9
    on_success: always
    on_failure: always
    on_start: true

after_success:
  - ./deploy_to_bintray.sh

before_deploy:
- gem install mime-types -v 2.6.2

deploy:
  provider: releases
  api_key:
    secure: RWpPmmzrJ2Ddx8nwG6k6UZm98o7gMRpGJ2liCFUGy5Uuf8w5AXj6xMLKFdcK3pZFSYBQ1+4DycFPAXmFCfP+nv6dX9PbDkOVB669ecnxStfVse0zXYgjuNEmhAht6wDb/O6jiNUrnyXcmQDExhXC3SigtnWcLUiRbJOYGoc3oSQ=
  file_glob: true
  file:
  - build/libs/*
  on:
    repo: restful-api-description-language/radl-specification
    tags: true
    all_branches: true
